from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.core.files import File
from rest_framework.permissions import AllowAny

import os

from .models import Dataset
from .services.ml_engine import MLPipeline


class DatasetUploadView(APIView):

    permission_classes = [AllowAny]

    def post(self, request):

        uploaded_file = request.FILES.get("file")

        if not uploaded_file:
            return Response(
                {"error": "No file uploaded."},
                status=status.HTTP_400_BAD_REQUEST
            )

        dataset = Dataset.objects.create(
            name=uploaded_file.name,
            original_file=uploaded_file,
            status="processing"
        )

        try:
            # Run ML pipeline
            pipeline = MLPipeline(dataset.original_file.path)
            results = pipeline.run()

            print("Pipeline results:", results)

            # GET CLEANED FILE PATH
            cleaned_path = results.get("cleaned_file_path")

            # SAVE CLEANED FILE INTO DJANGO MODEL
            if cleaned_path and os.path.exists(cleaned_path):

                file_name = os.path.basename(cleaned_path)

                with open(cleaned_path, "rb") as f:
                    dataset.cleaned_file.save(
                        file_name,
                        File(f),
                        save=False
                    )
                # Cleanup the duplicate file generated by ML pipeline
                os.remove(cleaned_path)

            # SAVE METRICS
            # Extract nested metrics
            metrics = results.get("metrics", {})
            raw_stats = results.get("raw_stats", {})
            cleaned_stats = results.get("cleaned_stats", {})
            cleaning_report = results.get("cleaning_report", {})

            # SAVE METRICS
            dataset.raw_accuracy = float(metrics.get("raw_score", 0))
            dataset.cleaned_accuracy = float(metrics.get("cleaned_score", 0))
            dataset.improvement = float(metrics.get("improvement", 0))

            dataset.status = "completed"
            dataset.save()

            # RETURN RESPONSE
            return Response(
                {
                    "message": "Pipeline executed successfully",
                    "dataset": dataset.name,
                    "metrics": {
                        "raw_accuracy": dataset.raw_accuracy,
                        "cleaned_accuracy": dataset.cleaned_accuracy,
                        "improvement": dataset.improvement
                    },
                    "raw_stats": raw_stats,
                    "cleaned_stats": cleaned_stats,
                    "cleaning_report": cleaning_report,
                    "cleaned_file_url": request.build_absolute_uri(dataset.cleaned_file.url)
                    if dataset.cleaned_file else None
                },
                status=status.HTTP_201_CREATED
            )

        except Exception as e:

            dataset.status = "failed"
            dataset.error_message = str(e)
            dataset.save()

            return Response(
                {"error": f"Pipeline failed: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )